import * as LucideIcons from 'lucide-react'

export const Icons = {
  Truck: LucideIcons.Truck,
  RefreshCw: LucideIcons.RefreshCw,
  ShieldCheck: LucideIcons.ShieldCheck,
  MessageCircle: LucideIcons.MessageCircle,
  ShoppingCart: LucideIcons.ShoppingCart,
  Menu: LucideIcons.Menu,
  X: LucideIcons.X,
  Search: LucideIcons.Search,
  Heart: LucideIcons.Heart,
  User: LucideIcons.User,
  ChevronDown: LucideIcons.ChevronDown,
  ChevronRight: LucideIcons.ChevronRight,
  ChevronLeft: LucideIcons.ChevronLeft,
  Star: LucideIcons.Star,
  Globe: LucideIcons.Globe,
  Package: LucideIcons.Package,
  Scale: LucideIcons.Scale,
  Zap: LucideIcons.Zap,
  Check: LucideIcons.Check,
  Plus: LucideIcons.Plus,
  Minus: LucideIcons.Minus,
  Trash2: LucideIcons.Trash2,
  Copy: LucideIcons.Copy,
  ExternalLink: LucideIcons.ExternalLink,
  Instagram: LucideIcons.Instagram,
  Facebook: LucideIcons.Facebook,
  Twitter: LucideIcons.Twitter,
  Youtube: LucideIcons.Youtube,
  TikTok: LucideIcons.TikTok,
  WhatsApp: LucideIcons.WhatsApp,
  Mail: LucideIcons.Mail,
  Eye: LucideIcons.Eye,
  EyeOff: LucideIcons.EyeOff,
  Filter: LucideIcons.Filter,
  Sliders: LucideIcons.Sliders,
  MapPin: LucideIcons.MapPin,
  Phone: LucideIcons.Phone,
  CreditCard: LucideIcons.CreditCard,
  DollarSign: LucideIcons.DollarSign,
  Lock: LucideIcons.Lock,
  Sparkles: LucideIcons.Sparkles,
}
