// Country, State/Province, City data for cascading dropdowns
// Major countries only - no island nations (except major ones like Japan, UK, NZ)
// Asia: Developed countries only (Japan, South Korea, Singapore, Taiwan, Hong Kong, Malaysia, Thailand, Vietnam)
// Americas: All North and South America countries
// Europe: All EU and major European countries

export interface Country {
  code: string
  name: string
  states: State[]
}

export interface State {
  code: string
  name: string
  cities: string[]
}

export const countries: Country[] = [
  // ============ NORTH AMERICA ============
  {
    code: 'US',
    name: 'United States',
    states: [
      { code: 'AL', name: 'Alabama', cities: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville'] },
      { code: 'AK', name: 'Alaska', cities: ['Anchorage', 'Fairbanks', 'Juneau'] },
      { code: 'AZ', name: 'Arizona', cities: ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale'] },
      { code: 'AR', name: 'Arkansas', cities: ['Little Rock', 'Fort Smith', 'Fayetteville'] },
      { code: 'CA', name: 'California', cities: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose'] },
      { code: 'CO', name: 'Colorado', cities: ['Denver', 'Boulder', 'Colorado Springs', 'Aurora'] },
      { code: 'CT', name: 'Connecticut', cities: ['Bridgeport', 'New Haven', 'Hartford', 'Stamford'] },
      { code: 'DE', name: 'Delaware', cities: ['Wilmington', 'Dover', 'Newark'] },
      { code: 'FL', name: 'Florida', cities: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale'] },
      { code: 'GA', name: 'Georgia', cities: ['Atlanta', 'Savannah', 'Augusta', 'Macon'] },
      { code: 'HI', name: 'Hawaii', cities: ['Honolulu'] },
      { code: 'ID', name: 'Idaho', cities: ['Boise', 'Meridian', 'Nampa'] },
      { code: 'IL', name: 'Illinois', cities: ['Chicago', 'Springfield', 'Rockford', 'Aurora'] },
      { code: 'IN', name: 'Indiana', cities: ['Indianapolis', 'Fort Wayne', 'Evansville'] },
      { code: 'IA', name: 'Iowa', cities: ['Des Moines', 'Cedar Rapids', 'Davenport'] },
      { code: 'KS', name: 'Kansas', cities: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka'] },
      { code: 'KY', name: 'Kentucky', cities: ['Louisville', 'Lexington', 'Bowling Green'] },
      { code: 'LA', name: 'Louisiana', cities: ['New Orleans', 'Baton Rouge', 'Shreveport'] },
      { code: 'ME', name: 'Maine', cities: ['Portland', 'Lewiston', 'Bangor'] },
      { code: 'MD', name: 'Maryland', cities: ['Baltimore', 'Columbia', 'Silver Spring'] },
      { code: 'MA', name: 'Massachusetts', cities: ['Boston', 'Worcester', 'Springfield', 'Cambridge'] },
      { code: 'MI', name: 'Michigan', cities: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Lansing'] },
      { code: 'MN', name: 'Minnesota', cities: ['Minneapolis', 'Saint Paul', 'Rochester'] },
      { code: 'MS', name: 'Mississippi', cities: ['Jackson', 'Gulfport', 'Southaven'] },
      { code: 'MO', name: 'Missouri', cities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia'] },
      { code: 'MT', name: 'Montana', cities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman'] },
      { code: 'NE', name: 'Nebraska', cities: ['Omaha', 'Lincoln', 'Bellevue'] },
      { code: 'NV', name: 'Nevada', cities: ['Las Vegas', 'Reno', 'Henderson', 'Carson City'] },
      { code: 'NH', name: 'New Hampshire', cities: ['Manchester', 'Nashua', 'Concord'] },
      { code: 'NJ', name: 'New Jersey', cities: ['Newark', 'Jersey City', 'Trenton', 'Camden'] },
      { code: 'NM', name: 'New Mexico', cities: ['Albuquerque', 'Las Cruces', 'Santa Fe', 'Rio Rancho'] },
      { code: 'NY', name: 'New York', cities: ['New York City', 'Buffalo', 'Rochester', 'Albany', 'Syracuse'] },
      { code: 'NC', name: 'North Carolina', cities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'] },
      { code: 'ND', name: 'North Dakota', cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot'] },
      { code: 'OH', name: 'Ohio', cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'] },
      { code: 'OK', name: 'Oklahoma', cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow'] },
      { code: 'OR', name: 'Oregon', cities: ['Portland', 'Eugene', 'Salem', 'Gresham'] },
      { code: 'PA', name: 'Pennsylvania', cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie'] },
      { code: 'RI', name: 'Rhode Island', cities: ['Providence', 'Warwick', 'Cranston'] },
      { code: 'SC', name: 'South Carolina', cities: ['Charleston', 'Columbia', 'North Charleston', 'Greenville'] },
      { code: 'SD', name: 'South Dakota', cities: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings'] },
      { code: 'TN', name: 'Tennessee', cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga'] },
      { code: 'TX', name: 'Texas', cities: ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth', 'El Paso'] },
      { code: 'UT', name: 'Utah', cities: ['Salt Lake City', 'Provo', 'West Valley City', 'Ogden'] },
      { code: 'VT', name: 'Vermont', cities: ['Burlington', 'South Burlington', 'Rutland'] },
      { code: 'VA', name: 'Virginia', cities: ['Virginia Beach', 'Norfolk', 'Richmond', 'Arlington', 'Newport News'] },
      { code: 'WA', name: 'Washington', cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'] },
      { code: 'WV', name: 'West Virginia', cities: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg'] },
      { code: 'WI', name: 'Wisconsin', cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha'] },
      { code: 'WY', name: 'Wyoming', cities: ['Cheyenne', 'Casper', 'Laramie', 'Gillette'] },
    ],
  },
  {
    code: 'CA',
    name: 'Canada',
    states: [
      { code: 'AB', name: 'Alberta', cities: ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge', 'Airdrie'] },
      { code: 'BC', name: 'British Columbia', cities: ['Vancouver', 'Victoria', 'Surrey', 'Burnaby', 'Richmond', 'Kelowna'] },
      { code: 'MB', name: 'Manitoba', cities: ['Winnipeg', 'Brandon', 'Steinbach', 'Portage la Prairie'] },
      { code: 'NB', name: 'New Brunswick', cities: ['Moncton', 'Saint John', 'Fredericton', 'Miramichi'] },
      { code: 'NL', name: 'Newfoundland and Labrador', cities: ["St. John's", 'Mount Pearl', 'Corner Brook', 'Grand Falls-Windsor'] },
      { code: 'NS', name: 'Nova Scotia', cities: ['Halifax', 'Sydney', 'Dartmouth', 'Truro'] },
      { code: 'ON', name: 'Ontario', cities: ['Toronto', 'Ottawa', 'Mississauga', 'Hamilton', 'London', 'Brampton', 'Kitchener'] },
      { code: 'PE', name: 'Prince Edward Island', cities: ['Charlottetown', 'Summerside', 'Stratford'] },
      { code: 'QC', name: 'Quebec', cities: ['Montreal', 'Quebec City', 'Laval', 'Gatineau', 'Sherbrooke'] },
      { code: 'SK', name: 'Saskatchewan', cities: ['Saskatoon', 'Regina', 'Moose Jaw', 'Swift Current', 'Yorkton'] },
    ],
  },
  {
    code: 'MX',
    name: 'Mexico',
    states: [
      { code: 'AGU', name: 'Aguascalientes', cities: ['Aguascalientes', 'Rincón de Romos', 'Pabellón de Arteaga'] },
      { code: 'BC', name: 'Baja California', cities: ['Tijuana', 'Mexicali', 'Ensenada', 'Tecate'] },
      { code: 'BCS', name: 'Baja California Sur', cities: ['La Paz', 'Los Cabos', 'Comondú'] },
      { code: 'CAM', name: 'Campeche', cities: ['San Francisco de Campeche', 'Carmen', 'Champotón'] },
      { code: 'CHP', name: 'Chiapas', cities: ['Tuxtla Gutiérrez', 'Tapachula', 'San Cristóbal de las Casas', 'Comitán'] },
      { code: 'CHH', name: 'Chihuahua', cities: ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Cuauhtémoc'] },
      { code: 'COA', name: 'Coahuila', cities: ['Saltillo', 'Monclova', 'Torreón', 'Piedras Negras', 'Ramos Arizpe'] },
      { code: 'COL', name: 'Colima', cities: ['Colima', 'Manzanillo', 'Tecomán', 'Villa de Álvarez'] },
      { code: 'DIF', name: 'Distrito Federal', cities: ['Mexico City'] },
      { code: 'DUR', name: 'Durango', cities: ['Durango', 'Victoria de Durango', 'Gómez Palacio', 'Lerdo'] },
      { code: 'GUA', name: 'Guanajuato', cities: ['León', 'Celaya', 'Irapuato', 'Salamanca', 'Guanajuato', 'Silao'] },
      { code: 'GRO', name: 'Guerrero', cities: ['Chilpancingo', 'Acapulco', 'Iguala', 'Taxco', 'Zihuatanejo'] },
      { code: 'HID', name: 'Hidalgo', cities: ['Pachuca', 'Tulancingo', 'Mineral de la Reforma', 'Huejutla'] },
      { code: 'JAL', name: 'Jalisco', cities: ['Guadalajara', 'Zapotlanejo', 'Tonalá', 'Puerto Vallarta', 'Lagos de Moreno'] },
      { code: 'MEX', name: 'Estado de México', cities: ['Ecatepec', 'Naucalpan', 'Tlalnepantla', 'Metepec', 'Toluca'] },
      { code: 'MIC', name: 'Michoacán', cities: ['Morelia', 'Uruapan', 'Lázaro Cárdenas', 'Zamora', 'Apatzingán'] },
      { code: 'MOR', name: 'Morelos', cities: ['Cuernavaca', 'Cuautla', 'Jiutepec', 'Temixco'] },
      { code: 'NAY', name: 'Nayarit', cities: ['Tepic', 'Bahía de Banderas', 'Santiago Ixcuintla', 'Compostela'] },
      { code: 'NLE', name: 'Nuevo León', cities: ['Monterrey', 'Guadalupe', 'San Nicolás', 'Apodaca', 'Santa Catarina'] },
      { code: 'OAX', name: 'Oaxaca', cities: ['Oaxaca', 'Santo Domingo Tehuantepec', 'Juchitán', 'Salina Cruz', 'Puerto Escondido'] },
      { code: 'PUE', name: 'Puebla', cities: ['Puebla', 'Tehuacán', 'Atlixco', 'San Andrés Cholula', 'Amozoc'] },
      { code: 'QUE', name: 'Querétaro', cities: ['Querétaro', 'San Juan del Río', 'El Marqués', 'Tequisquiapan'] },
      { code: 'ROO', name: 'Quintana Roo', cities: ['Cancún', 'Chetumal', 'Playa del Carmen', 'Cozumel', 'Tulum'] },
      { code: 'SLP', name: 'San Luis Potosí', cities: ['San Luis Potosí', 'Soledad de Graciano Sánchez', 'Matehuala', 'Ciudad Valles'] },
      { code: 'SIN', name: 'Sinaloa', cities: ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guasave', 'Escuinapa'] },
      { code: 'SON', name: 'Sonora', cities: ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'San Luis Río Colorado', 'Guaymas'] },
      { code: 'TAB', name: 'Tabasco', cities: ['Villahermosa', 'Cárdenas', 'Huimanguillo', 'Comalcalco', 'Macuspana'] },
      { code: 'TAM', name: 'Tamaulipas', cities: ['Reynosa', 'Nuevo Laredo', 'Matamoros', 'Ciudad Victoria', 'Tampico'] },
      { code: 'TLA', name: 'Tlaxcala', cities: ['Tlaxcala', 'Apizaco', 'Calpulalpan', 'Chiautempan', 'Papalotla'] },
      { code: 'VER', name: 'Veracruz', cities: ['Veracruz', 'Xalapa', 'Córdoba', 'Boca del Río', 'Orizaba', 'Coatzacoalcos'] },
      { code: 'YUC', name: 'Yucatán', cities: ['Mérida', 'Valladolid', 'Tizimín', 'Kanasín', 'Progreso'] },
      { code: 'ZAC', name: 'Zacatecas', cities: ['Zacatecas', 'Fresnillo', 'Guadalupe', 'Río Grande', 'Sombrerete'] },
    ],
  },

  // ============ SOUTH AMERICA ============
  {
    code: 'AR',
    name: 'Argentina',
    states: [
      { code: 'BA', name: 'Buenos Aires', cities: ['Buenos Aires', 'La Plata', 'Mar del Plata', 'Quilmes', 'Bahía Blanca'] },
      { code: 'CB', name: 'Córdoba', cities: ['Córdoba', 'Villa María', 'Río Cuarto', 'San Francisco'] },
      { code: 'SF', name: 'Santa Fe', cities: ['Rosario', 'Santa Fe', 'Venado Tuerto', 'Rafaela'] },
      { code: 'MZ', name: 'Mendoza', cities: ['Mendoza', 'San Rafael', 'Godoy Cruz', 'Guaymallén'] },
      { code: 'TU', name: 'Tucumán', cities: ['San Miguel de Tucumán', 'Tafí Viejo', 'Banda del Río Salí'] },
      { code: 'EN', name: 'Entre Ríos', cities: ['Paraná', 'Concordia', 'Gualeguaychú'] },
      { code: 'CO', name: 'Corrientes', cities: ['Corrientes', 'Goya', 'Mercedes'] },
      { code: 'MI', name: 'Misiones', cities: ['Posadas', 'Oberá', 'Eldorado', 'Puerto Iguazú'] },
      { code: 'JU', name: 'Jujuy', cities: ['San Salvador de Jujuy', 'San Pedro', 'Libertador'] },
      { code: 'RN', name: 'Río Negro', cities: ['Viedma', 'Bariloche', 'General Roca', 'Cipolletti'] },
      { code: 'CH', name: 'Chaco', cities: ['Resistencia', 'Presidencia Roque Sáenz Peña'] },
      { code: 'SL', name: 'San Luis', cities: ['San Luis', 'Villa Mercedes', 'La Punta'] },
      { code: 'CR', name: 'Catamarca', cities: ['San Fernando del Valle de Catamarca', 'Andalgalá'] },
      { code: 'LR', name: 'La Rioja', cities: ['La Rioja', 'Chilecito', 'Aimogasta'] },
      { code: 'SQ', name: 'Santiago del Estero', cities: ['Santiago del Estero', 'La Banda', 'Termas de Río Hondo'] },
      { code: 'TF', name: 'Tierra del Fuego', cities: ['Ushuaia', 'Río Grande'] },
      { code: 'SC', name: 'Santa Cruz', cities: ['Río Gallegos', 'Caleta Olivia', 'Puerto Deseado'] },
    ],
  },
  {
    code: 'BR',
    name: 'Brazil',
    states: [
      { code: 'SP', name: 'São Paulo', cities: ['São Paulo', 'Campinas', 'Santos', 'São Bernardo', 'São José'] },
      { code: 'RJ', name: 'Rio de Janeiro', cities: ['Rio de Janeiro', 'São Gonçalo', 'Duque de Caxias', 'Nova Iguaçu'] },
      { code: 'MG', name: 'Minas Gerais', cities: ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Betim', 'Juiz de Fora'] },
      { code: 'DF', name: 'Distrito Federal', cities: ['Brasília', 'Taguatinga', 'Ceilândia', 'Samambaia'] },
      { code: 'RS', name: 'Rio Grande do Sul', cities: ['Porto Alegre', 'Caxias do Sul', 'Pelotas', 'Canoas'] },
      { code: 'PR', name: 'Paraná', cities: ['Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa', 'Cascavel'] },
      { code: 'SC', name: 'Santa Catarina', cities: ['Florianópolis', 'Joinville', 'Blumenau', 'São José', 'Criciúma'] },
      { code: 'BA', name: 'Bahia', cities: ['Salvador', 'Feira de Santana', 'Vitória da Conquista', 'Camaçari'] },
      { code: 'PE', name: 'Pernambuco', cities: ['Recife', 'Jaboatão dos Guararapes', 'Olinda', 'Caruaru'] },
      { code: 'CE', name: 'Ceará', cities: ['Fortaleza', 'Caucaia', 'Juazeiro do Norte', 'Maracanaú'] },
      { code: 'GO', name: 'Goiás', cities: ['Goiânia', 'Anápolis', 'Aparecida de Goiânia', 'Luziânia'] },
      { code: 'PA', name: 'Pará', cities: ['Belém', 'Ananindeua', 'Santarém', 'Marabá'] },
      { code: 'MA', name: 'Maranhão', cities: ['São Luís', 'Imperatriz', 'Timon', 'Caxias'] },
      { code: 'AM', name: 'Amazonas', cities: ['Manaus', 'Parintins', 'Itacoatiara'] },
      { code: 'PB', name: 'Paraíba', cities: ['João Pessoa', 'Campina Grande', 'Santa Rita', 'Patos'] },
      { code: 'RN', name: 'Rio Grande do Norte', cities: ['Natal', 'Mossoró', 'Parnamirim'] },
      { code: 'AL', name: 'Alagoas', cities: ['Maceió', 'Arapiraca', 'Rio Largo'] },
      { code: 'PI', name: 'Piauí', cities: ['Teresina', 'Parnaíba', 'Piripiri'] },
      { code: 'MT', name: 'Mato Grosso', cities: ['Cuiabá', 'Várzea Grande', 'Rondonópolis', 'Sinop'] },
      { code: 'MS', name: 'Mato Grosso do Sul', cities: ['Campo Grande', 'Dourados', 'Três Lagoas'] },
      { code: 'ES', name: 'Espírito Santo', cities: ['Vitória', 'Vila Velha', 'Serra', 'Cariacica'] },
      { code: 'SE', name: 'Sergipe', cities: ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto'] },
      { code: 'RO', name: 'Rondônia', cities: ['Porto Velho', 'Ji-Paraná', 'Ariquemes', 'Vilhena'] },
      { code: 'TO', name: 'Tocantins', cities: ['Palmas', 'Araguaína', 'Gurupi'] },
    ],
  },
  {
    code: 'CL',
    name: 'Chile',
    states: [
      { code: 'RM', name: 'Santiago', cities: ['Santiago', 'Puente Alto', 'Maipú', 'La Florida', 'Las Condes'] },
      { code: 'VS', name: 'Valparaíso', cities: ['Valparaíso', 'Viña del Mar', 'Quilpué', 'Villa Alemana'] },
      { code: 'BI', name: 'Bío Bío', cities: ['Concepción', 'Talcahuano', 'Chiguayante', 'Coronel'] },
      { code: 'AR', name: 'Araucanía', cities: ['Temuco', 'Padre las Casas', 'Villarrica'] },
      { code: 'LL', name: 'Los Lagos', cities: ['Puerto Montt', 'Osorno', 'Valdivia'] },
      { code: 'CO', name: 'Coquimbo', cities: ['La Serena', 'Coquimbo', 'Ovalle', 'Illapel'] },
      { code: 'ML', name: 'Maule', cities: ['Talca', 'Curicó', 'Linares', 'Cauquenes'] },
    ],
  },
  {
    code: 'CO',
    name: 'Colombia',
    states: [
      { code: 'DC', name: 'Bogotá D.C.', cities: ['Bogotá', 'Soacha', 'Chía', 'Cota'] },
      { code: 'AN', name: 'Antioquia', cities: ['Medellín', 'Bello', 'Itagüí', 'Envigado', 'Rionegro'] },
      { code: 'VC', name: 'Valle del Cauca', cities: ['Cali', 'Palmira', 'Buenaventura', 'Tuluá', 'Buga'] },
      { code: 'AT', name: 'Atlántico', cities: ['Barranquilla', 'Soledad', 'Malambo', 'Sabanalarga'] },
      { code: 'CN', name: 'Cundinamarca', cities: ['Zipaquirá', 'Facatativá', 'Girardot', 'Mosquera'] },
      { code: 'SA', name: 'Santander', cities: ['Bucaramanga', 'Floridablanca', 'Girón', 'Piedecuesta'] },
      { code: 'HO', name: 'Huila', cities: ['Neiva', 'Pitalito', 'Garzón', 'La Plata'] },
      { code: 'BO', name: 'Bolívar', cities: ['Cartagena', 'Magangué', 'El Carmen de Bolívar'] },
      { code: 'NS', name: 'Nariño', cities: ['Pasto', 'Ipiales', 'Tumaco', 'Túquerres'] },
      { code: 'Tol', name: 'Tolima', cities: ['Ibagué', 'Melgar', 'Espinal', 'Honda'] },
      { code: 'NA', name: 'Norte de Santander', cities: ['Cúcuta', 'Ocaña', 'Pamplona'] },
      { code: 'CA', name: 'Cauca', cities: ['Popayán', 'Santander de Quilichao', 'Patía'] },
      { code: 'MAG', name: 'Magdalena', cities: ['Santa Marta', 'Ciénaga', 'Fundación'] },
      { code: 'RIS', name: 'Risaralda', cities: ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal'] },
      { code: 'QUI', name: 'Quindío', cities: ['Armenia', 'Calarcá', 'La Tebaida'] },
      { code: 'CAL', name: 'Caldas', cities: ['Manizales', 'La Dorada', 'Chinchiná'] },
    ],
  },
  },
  {
    code: 'PE',
    name: 'Peru',
    states: [
      { code: 'LIM', name: 'Lima', cities: ['Lima', 'Callao', 'San Juan de Lurigancho', 'San Martín de Porres'] },
      { code: 'ARE', name: 'Arequipa', cities: ['Arequipa', 'Camaná', 'Mollendo'] },
      { code: 'CUZ', name: 'Cusco', cities: ['Cusco', 'Quillabamba', 'Tinta'] },
      { code: 'TRU', name: 'La Libertad', cities: ['Trujillo', 'Chepén', 'Pacasmayo'] },
      { code: 'LAL', name: 'Lambayeque', cities: ['Chiclayo', 'Lambayeque', 'Ferreñafe'] },
      { code: 'PIU', name: 'Piura', cities: ['Piura', 'Sullana', 'Talara', 'Paita'] },
      { code: 'ANC', name: 'Ancash', cities: ['Huaraz', 'Chimbote', 'Nuevo Chimbote'] },
      { code: 'JUN', name: 'Junín', cities: ['Huancayo', 'Tarma', 'Jauja'] },
      { code: 'AYC', name: 'Ayacucho', cities: ['Ayacucho', 'Huanta', 'Puquio'] },
      { code: 'APU', name: 'Apurímac', cities: ['Abancay', 'Andahuaylas'] },
    ],
  },

  // ============ EUROPE ============
  {
    code: 'AL',
    name: 'Albania',
    states: [
      { code: 'TR', name: 'Tirana', cities: ['Tirana', 'Kamëz', 'Krujë', 'Vorë'] },
      { code: 'DR', name: 'Durrës', cities: ['Durrës', 'Shijak', 'Krujë'] },
      { code: 'VL', name: 'Vlorë', cities: ['Vlorë', 'Sarandë', 'Himarë'] },
      { code: 'SH', name: 'Shkodër', cities: ['Shkodër', 'Pukë', 'Lezhë'] },
    ],
  },
  {
    code: 'AD',
    name: 'Andorra',
    states: [
      { code: 'AN', name: 'Andorra la Vella', cities: ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'Sant Julià de Lòria'] },
    ],
  },
  {
    code: 'AT',
    name: 'Austria',
    states: [
      { code: 'VI', name: 'Vienna', cities: ['Vienna'] },
      { code: 'ST', name: 'Styria', cities: ['Graz', 'Leoben', 'Bruck an der Mur', 'Kapfenberg'] },
      { code: 'SZ', name: 'Salzburg', cities: ['Salzburg', 'Hallein', 'Saalfelden', 'Zell am See'] },
      { code: 'TI', name: 'Tyrol', cities: ['Innsbruck', 'Kufstein', 'Kitzbühel', 'Landeck'] },
      { code: 'OO', name: 'Upper Austria', cities: ['Linz', 'Wels', 'Steyr', 'Leonding', 'Traun'] },
      { code: 'NO', name: 'Lower Austria', cities: ['St. Pölten', 'Baden', 'Klosterneuburg', 'Krems', 'Tulln'] },
      { code: 'BU', name: 'Burgenland', cities: ['Eisenstadt', 'Mattersburg', 'Neusiedl an der Zaya'] },
      { code: 'CA', name: 'Carinthia', cities: ['Klagenfurt', 'Villach', 'Wolfsberg', 'Spittal an der Drau'] },
      { code: 'VO', name: 'Vorarlberg', cities: ['Bregenz', 'Dornbirn', 'Feldkirch', 'Bludenz'] },
    ],
  },
  {
    code: 'BE',
    name: 'Belgium',
    states: [
      { code: 'BRU', name: 'Brussels', cities: ['Brussels', ' Schaerbeek'] },
      { code: 'VAN', name: 'Antwerp', cities: ['Antwerp', 'Mechelen', 'Kortrijk', 'Hasselt', 'Aalst'] },
      { code: 'WAL', name: 'Wallonia', cities: ['Charleroi', 'Liège', 'Namur', 'Mons', 'La Louvière'] },
    ],
  },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    states: [
      { code: 'FB', name: 'Federation of Bosnia and Herzegovina', cities: ['Sarajevo', 'Mostar', 'Tuzla', 'Zenica'] },
      { code: 'RS', name: 'Republika Srpska', cities: ['Banja Luka', 'Prijedor', 'Derventa', 'Laktaši'] },
    ],
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    states: [
      { code: 'S', name: 'Sofia', cities: ['Sofia', 'Pernik', 'Bozurishte'] },
      { code: 'PD', name: 'Plovdiv', cities: ['Plovdiv', 'Asenovgrad', 'Karlovo'] },
      { code: 'V', name: 'Varna', cities: ['Varna', 'Dobrich', 'Kavarna'] },
      { code: 'B', name: 'Burgas', cities: ['Burgas', 'Sliven', 'Yambol'] },
      { code: 'ST', name: 'Stara Zagora', cities: ['Stara Zagora', 'Kazandlak', 'Chirpan'] },
      { code: 'R', name: 'Ruse', cities: ['Ruse', 'Byala', 'Tutrakan'] },
      { code: 'H', name: 'Haskovo', cities: ['Haskovo', 'Dimitrovgrad', 'Harmanli'] },
    ],
  },
  {
    code: 'BY',
    name: 'Belarus',
    states: [
      { code: 'MI', name: 'Minsk', cities: ['Minsk', 'Barysaw', 'Maladziečna', 'Zhodzina'] },
      { code: 'VI', name: 'Vitebsk', cities: ['Vitebsk', 'Navapolatsk', 'Orsha', 'Polotsk'] },
      { code: 'HO', name: 'Grodno', cities: ['Grodno', 'Lida', 'Vaukavysk'] },
      { code: 'HR', name: 'Gomel', cities: ['Gomel', 'Mazyr', 'Rechytsa'] },
      { code: 'BR', name: 'Brest', cities: ['Brest', 'Baranavichy', 'Pinsk'] },
      { code: 'MA', name: 'Mogilev', cities: ['Mogilev', 'Babruysk', 'Horki'] },
    ],
  },
  {
    code: 'HR',
    name: 'Croatia',
    states: [
      { code: 'GZ', name: 'Zagreb', cities: ['Zagreb', 'Velika Gorica', 'Samobor', 'Sesvete'] },
      { code: 'SP', name: 'Split-Dalmatia', cities: ['Split', 'Solin', 'Kaštela', 'Trogir'] },
      { code: 'RI', name: 'Primorje-Gorski Kotar', cities: ['Rijeka', 'Opatija', 'Crikvenica'] },
      { code: 'OS', name: 'Osijek-Baranja', cities: ['Osijek', 'Đakovo', 'Našice', 'Vukovar'] },
      { code: 'ZD', name: 'Zadar', cities: ['Zadar', 'Biograd na Moru', 'Nin'] },
      { code: 'SI', name: 'Šibenik-Knin', cities: ['Šibenik', 'Vodice'] },
      { code: 'IS', name: 'Istria', cities: ['Pula', 'Rijeka', 'Poreč', 'Rovinj'] },
    ],
  },
  {
    code: 'CY',
    name: 'Cyprus',
    states: [
      { code: 'NIC', name: 'Nicosia', cities: ['Nicosia', 'Kyrenia', 'Famagusta', 'Morphou'] },
      { code: 'LIM', name: 'Limassol', cities: ['Limassol', 'Yermasoyia', 'Kato Polemidia'] },
      { code: 'LAR', name: 'Larnaca', cities: ['Larnaca', 'Famagusta', 'Aradippou'] },
      { code: 'PFO', name: 'Paphos', cities: ['Paphos', 'Polis', 'Yeroskipou'] },
    ],
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    states: [
      { code: 'PR', name: 'Prague', cities: ['Prague'] },
      { code: 'JM', name: 'South Moravia', cities: ['Brno', 'Znojmo', 'Břeclav', 'Hodonín'] },
      { code: 'MO', name: 'Moravia-Silesia', cities: ['Ostrava', 'Opava', 'Karviná', 'Havířov'] },
      { code: 'UL', name: 'Ústí nad Labem', cities: ['Ústí nad Labem', 'Most', 'Chomutov', 'Děčín'] },
      { code: 'HK', name: 'Hradec Králové', cities: ['Hradec Králové', 'Trutnov', 'Náchod'] },
      { code: 'LI', name: 'Liberec', cities: ['Liberec', 'Jablonec nad Nisou', 'Česká Lípa'] },
      { code: 'OL', name: 'Olomouc', cities: ['Olomouc', 'Prostějov', 'Přerov', 'Kroměříž'] },
      { code: 'PLZ', name: 'Plzeň', cities: ['Plzeň', 'Klatovy', 'Tachov'] },
      { code: 'STC', name: 'Central Bohemian', cities: ['Kladno', 'Mladá Boleslav', 'Příbram', 'Kolín'] },
      { code: 'JHC', name: 'South Bohemian', cities: ['České Budějovice', 'Tábor', 'Písek', 'Strakonice'] },
      { code: 'VYS', name: 'Vysočina', cities: ['Jihlava', 'Havličkův Brod', 'Žďár nad Sázavou'] },
      { code: 'ZLI', name: 'Zlín', cities: ['Zlín', 'Kroměříž', 'Vsetín', 'Valašské Meziříčí'] },
    ],
  },
  {
    code: 'DK',
    name: 'Denmark',
    states: [
      { code: 'DK', name: 'Capital Region', cities: ['Copenhagen', 'Frederiksberg', 'Gentofte', 'Gladsaxe'] },
      { code: 'AR', name: 'Central Jutland', cities: ['Aarhus', 'Randers', 'Silkeborg', 'Horsens'] },
      { code: 'OD', name: 'Southern Denmark', cities: ['Odense', 'Svendborg', 'Kerteminde', 'Middelfart'] },
      { code: 'RK', name: 'Zealand', cities: ['Roskilde', 'Frederikssund', 'Køge', 'Næstved'] },
      { code: 'NS', name: 'North Denmark', cities: ['Aalborg', 'Hjørring', 'Frederikshavn', 'Thisted'] },
    ],
  },
  {
    code: 'EE',
    name: 'Estonia',
    states: [
      { code: 'TA', name: 'Tallinn', cities: ['Tallinn', 'Tartu', 'Pärnu', 'Narva'] },
      { code: 'HAR', name: 'Harju', cities: ['Tallinn', 'Keila', 'Saue', 'Harku'] },
      { code: 'TAR', name: 'Tartu', cities: ['Tartu', 'Elva', 'Võru', 'Viljandi'] },
    ],
  },
  {
    code: 'FI',
    name: 'Finland',
    states: [
      { code: 'UF', name: 'Uusimaa', cities: ['Helsinki', 'Espoo', 'Vantaa', 'Kauniainen', 'Kerava'] },
      { code: 'TR', name: 'Tampere', cities: ['Tampere', 'Hämeenlinna', 'Lahti', 'Valkeakoski'] },
      { code: 'TK', name: 'Turku', cities: ['Turku', 'Porvoo', 'Kaarina', 'Raisio'] },
      { code: 'OU', name: 'Oulu', cities: ['Oulu', 'Kajaani', 'Rovaniemi', 'Kemi'] },
      { code: 'JY', name: 'Jyväskylä', cities: ['Jyväskylä', 'Kuopio', 'Vaasa', 'Seinäjoki'] },
      { code: 'LO', name: 'Lappeenranta', cities: ['Lappeenranta', 'Imatra', 'Kotka', 'Kouvola'] },
    ],
  },
  {
    code: 'FR',
    name: 'France',
    states: [
      { code: 'IDF', name: 'Île-de-France', cities: ['Paris', 'Saint-Denis', 'Boulogne-Billancourt', 'Argenteuil', 'Montreuil'] },
      { code: 'ARA', name: 'Auvergne-Rhône-Alpes', cities: ['Lyon', 'Saint-Étienne', 'Grenoble', 'Villeurbanne', 'Clermont-Ferrand'] },
      { code: 'PAC', name: 'Provence-Alpes-Côte d\'Azur', cities: ['Marseille', 'Nice', 'Toulon', 'Aix-en-Provence', 'Avignon'] },
      { code: 'OCC', name: 'Occitanie', cities: ['Toulouse', 'Montpellier', 'Nîmes', 'Perpignan', 'Béziers'] },
      { code: 'HDF', name: 'Hauts-de-France', cities: ['Lille', 'Amiens', 'Roubaix', 'Tourcoing'] },
      { code: 'GES', name: 'Grand Est', cities: ['Strasbourg', 'Reims', 'Metz', 'Mulhouse', 'Colmar'] },
      { code: 'NAQ', name: 'Nouvelle-Aquitaine', cities: ['Bordeaux', 'Limoges', 'Poitiers', 'La Rochelle', 'Pau'] },
      { code: 'BRE', name: 'Brittany', cities: ['Rennes', 'Brest', 'Quimper', 'Lorient', 'Vannes'] },
      { code: 'CVL', name: 'Centre-Val de Loire', cities: ['Tours', 'Orléans', 'Bourges', 'Blois', 'Chartres'] },
      { code: 'BFC', name: 'Bourgogne-Franche-Comté', cities: ['Dijon', 'Besançon', 'Belfort', 'Chalon-sur-Saône'] },
      { code: 'NOR', name: 'Normandy', cities: ['Rouen', 'Caen', 'Le Havre', 'Cherbourg'] },
      { code: 'PDL', name: 'Pays de la Loire', cities: ['Nantes', 'Angers', 'Le Mans', 'Saint-Nazaire'] },
    ],
  },
  {
    code: 'DE',
    name: 'Germany',
    states: [
      { code: 'BY', name: 'Bavaria', cities: ['Munich', 'Nuremberg', 'Augsburg', 'Regensburg', 'Würzburg'] },
      { code: 'BE', name: 'Berlin', cities: ['Berlin'] },
      { code: 'HH', name: 'Hamburg', cities: ['Hamburg'] },
      { code: 'HE', name: 'Hesse', cities: ['Frankfurt', 'Wiesbaden', 'Darmstadt', 'Kassel'] },
      { code: 'NW', name: 'North Rhine-Westphalia', cities: ['Cologne', 'Düsseldorf', 'Dortmund', 'Essen', 'Duisburg', 'Bonn'] },
      { code: 'BW', name: 'Baden-Württemberg', cities: ['Stuttgart', 'Karlsruhe', 'Mannheim', 'Freiburg', 'Heidelberg'] },
      { code: 'NI', name: 'Lower Saxony', cities: ['Hanover', 'Braunschweig', 'Oldenburg', 'Osnabrück', 'Wolfsburg'] },
      { code: 'SN', name: 'Saxony', cities: ['Dresden', 'Leipzig', 'Chemnitz', 'Zwickau'] },
      { code: 'RP', name: 'Rhineland-Palatinate', cities: ['Mainz', 'Koblenz', 'Trier', 'Kaiserslautern'] },
      { code: 'SH', name: 'Schleswig-Holstein', cities: ['Kiel', 'Lübeck', 'Flensburg', 'Neumünster'] },
      { code: 'HB', name: 'Bremen', cities: ['Bremen', 'Bremerhaven'] },
      { code: 'BB', name: 'Brandenburg', cities: ['Potsdam', 'Cottbus', 'Brandenburg an der Havel'] },
      { code: 'ST', name: 'Saxony-Anhalt', cities: ['Magdeburg', 'Halle', 'Dessau', 'Wittenberg'] },
      { code: 'TH', name: 'Thuringia', cities: ['Erfurt', 'Jena', 'Gera', 'Weimar'] },
      { code: 'MV', name: 'Mecklenburg-Vorpommern', cities: ['Rostock', 'Schwerin', 'Neubrandenburg', 'Stralsund'] },
    ],
  },
  {
    code: 'GR',
    name: 'Greece',
    states: [
      { code: 'AT', name: 'Attica', cities: ['Athens', 'Piraeus', 'Glyfada', 'Marousi', 'Kallithea'] },
      { code: 'TH', name: 'Thessaloniki', cities: ['Thessaloniki', 'Kalamaria', 'Stavropolis'] },
      { code: 'CR', name: 'Crete', cities: ['Heraklion', 'Chania', 'Rethymno', 'Agios Nikolaos'] },
      { code: 'AX', name: 'Central Greece', cities: ['Athens', 'Piraeus', 'Peristeri', 'Kallithea'] },
      { code: 'EP', name: 'Epirus', cities: ['Ioannina', 'Arta', 'Preveza', 'Igoumenitsa'] },
      { code: 'THES', name: 'Thessaly', cities: ['Larissa', 'Volos', 'Karditsa', 'Trikala'] },
      { code: 'MAC', name: 'Macedonia', cities: ['Thessaloniki', 'Kavala', 'Xanthi', 'Drama', 'Serres'] },
      { code: 'PEL', name: 'Peloponnese', cities: ['Patras', 'Kalamata', 'Sparta', 'Tripoli', 'Korinth'] },
      { code: 'ION', name: 'Ionian Islands', cities: ['Corfu', 'Zakynthos', 'Lefkada', 'Kefalonia'] },
      { code: 'AE', name: 'Aegean Islands', cities: ['Rhodes', 'Lesbos', 'Samos', 'Chios', 'Kos'] },
    ],
  },
  {
    code: 'HU',
    name: 'Hungary',
    states: [
      { code: 'BU', name: 'Budapest', cities: ['Budapest', 'Budapest I', 'Budapest II', 'Budapest III', 'Budapest IV', 'Budapest V', 'Budapest VI', 'Budapest VII', 'Budapest VIII', 'Budapest IX', 'Budapest X', 'Budapest XI', 'Budapest XII', 'Budapest XIII', 'Budapest XIV', 'Budapest XV', 'Budapest XVI', 'Budapest XVII', 'Budapest XVIII', 'Budapest XIX', 'Budapest XX', 'Budapest XXI', 'Budapest XXII', 'Budapest XXIII'] },
      { code: 'PE', name: 'Pest', cities: ['Érd', 'Dunakeszi', 'Szigetszentmiklós', 'Cegléd', 'Szentendre'] },
      { code: 'GY', name: 'Győr-Moson-Sopron', cities: ['Győr', 'Sopron', 'Mosonmagyaróvár', 'Kapuvár'] },
      { code: 'DE', name: 'Debrecen', cities: ['Debrecen', 'Hajdúszoboszló', 'Balmazújváros'] },
      { code: 'SZ', name: 'Szeged', cities: ['Szeged', 'Hódmezővásárhely', 'Makó', 'Szentes'] },
      { code: 'MI', name: 'Miskolc', cities: ['Miskolc', 'Ózd', 'Kazincbarcika', 'Salgótarján'] },
      { code: 'PA', name: 'Pécs', cities: ['Pécs', 'Komló', 'Szigetvár', 'Mohács'] },
      { code: 'BA', name: 'Bács-Kiskun', cities: ['Kecskemét', 'Baja', 'Kalocsa', 'Kiskunfélegyháza'] },
      { code: 'SM', name: 'Szabolcs-Szatmár-Bereg', cities: ['Nyíregyháza', 'Mátészalka', 'Kisvárda', 'Nyírbátor'] },
    ],
  },
  {
    code: 'IS',
    name: 'Iceland',
    states: [
      { code: 'RF', name: 'Capital Region', cities: ['Reykjavik', 'Kópavogur', 'Hafnarfjörður', 'Garðabær'] },
      { code: 'SU', name: 'Southern Peninsula', cities: ['Keflavík', 'Njarðvík', 'Reykjanesbær'] },
      { code: 'VF', name: 'Westfjords', cities: ['Ísafjörður', 'Patreksfjörður', 'Hólmavík'] },
      { code: 'AE', name: 'Eastern', cities: ['Egilsstaðir', 'Seyðisfjörður', 'Hornsland'] },
      { code: 'SU', name: 'Southern', cities: ['Vík', 'Höfn', 'Kirkjubæjarklaustur'] },
      { code: 'NO', name: 'North', cities: ['Akureyri', 'Húsavík', 'Siglufjörður'] },
      { code: 'OL', name: 'West', cities: ['Borgarnes', 'Stykkishólmur', 'Ólafsvík'] },
    ],
  },
  {
    code: 'IE',
    name: 'Ireland',
    states: [
      { code: 'D', name: 'Dublin', cities: ['Dublin', 'South Dublin', 'Fingal', 'Dún Laoghaire–Rathdown'] },
      { code: 'C', name: 'Cork', cities: ['Cork', 'Cobh', 'Midleton', 'Mallow', 'Kinsale'] },
      { code: 'G', name: 'Galway', cities: ['Galway', 'Tuam', 'Loughrea', 'Clifden'] },
      { code: 'L', name: 'Limerick', cities: ['Limerick', 'Shannon', 'Newcastle West'] },
      { code: 'W', name: 'Waterford', cities: ['Waterford', 'Tramore', 'Dungarvan'] },
      { code: 'WEX', name: 'Wexford', cities: ['Wexford', 'Enniscorthy', 'New Ross', 'Gorey'] },
      { code: 'K', name: 'Kildare', cities: ['Naas', 'Newbridge', 'Celbridge', 'Leixlip', 'Maynooth'] },
      { code: 'WICK', name: 'Wicklow', cities: ['Bray', 'Wicklow', 'Arklow', 'Greystones'] },
      { code: 'M', name: 'Meath', cities: ['Navan', 'Trim', 'Kells', 'Dunboyne'] },
      { code: 'LH', name: 'Louth', cities: ['Dundalk', 'Drogheda', 'Ardee'] },
    ],
  },
  {
    code: 'IT',
    name: 'Italy',
    states: [
      { code: 'LAZ', name: 'Lazio', cities: ['Rome', 'Latina', 'Fiumicino', 'Guidonia', 'Aprilia'] },
      { code: 'LOM', name: 'Lombardy', cities: ['Milan', 'Brescia', 'Monza', 'Bergamo', 'Como', 'Varese'] },
      { code: 'CAM', name: 'Campania', cities: ['Naples', 'Salerno', 'Giugliano', 'Torre del Greco', 'Pozzuoli'] },
      { code: 'VEN', name: 'Veneto', cities: ['Venice', 'Verona', 'Padua', 'Treviso', 'Vicenza'] },
      { code: 'SIC', name: 'Sicily', cities: ['Palermo', 'Catania', 'Messina', 'Siracusa', 'Marsala'] },
      { code: 'EMR', name: 'Emilia-Romagna', cities: ['Bologna', 'Modena', 'Parma', 'Reggio Emilia', 'Ravenna'] },
      { code: 'PIE', name: 'Piedmont', cities: ['Turin', 'Novara', 'Alessandria', 'Asti', 'Cuneo'] },
      { code: 'TOS', name: 'Tuscany', cities: ['Florence', 'Prato', 'Livorno', 'Arezzo', 'Pisa', 'Siena'] },
      { code: 'PUG', name: 'Apulia', cities: ['Bari', 'Taranto', 'Foggia', 'Lecce', 'Brindisi'] },
      { code: 'CAL', name: 'Calabria', cities: ['Catanzaro', 'Reggio Calabria', 'Cosenza', 'Crotone'] },
      { code: 'SAR', name: 'Sardinia', cities: ['Cagliari', 'Sassari', 'Quartu Sant\'Elena', 'Olbia'] },
      { code: 'LIG', name: 'Liguria', cities: ['Genoa', 'La Spezia', 'Savona', 'Sanremo'] },
      { code: 'MAR', name: 'Marche', cities: ['Ancona', 'Macerata', 'Pesaro', 'Ascoli Piceno'] },
      { code: 'UMB', name: 'Umbria', cities: ['Perugia', 'Terni', 'Foligno', 'Gubbio'] },
      { code: 'ABR', name: 'Abruzzo', cities: ['L\'Aquila', 'Pescara', 'Teramo', 'Chieti'] },
      { code: 'FVG', name: 'Friuli-Venezia Giulia', cities: ['Trieste', 'Udine', 'Pordenone', 'Gorizia'] },
      { code: 'TRV', name: 'Trentino-Alto Adige', cities: ['Trento', 'Bolzano', 'Merano', 'Rovereto'] },
      { code: 'BAS', name: 'Basilicata', cities: ['Potenza', 'Matera', 'Melfi'] },
      { code: 'MOL', name: 'Molise', cities: ['Campobasso', 'Isernia', 'Termoli'] },
    ],
  },
  {
    code: 'XK',
    name: 'Kosovo',
    states: [
      { code: 'PR', name: 'Pristina', cities: ['Pristina', 'Podujeva', 'Glogovac'] },
      { code: 'PZ', name: 'Prizren', cities: ['Prizren', 'Gjakova', 'Rahovec'] },
      { code: 'GJ', name: 'Gjakova', cities: ['Gjakova', 'Rahovec', 'Junik'] },
    ],
  },
  {
    code: 'LV',
    name: 'Latvia',
    states: [
      { code: 'RIX', name: 'Riga', cities: ['Riga', 'Jūrmala', 'Ogre', 'Ādaži'] },
      { code: 'DAU', name: 'Daugavpils', cities: ['Daugavpils', 'Liepāja', 'Jelgava'] },
    ],
  },
  {
    code: 'LI',
    name: 'Liechtenstein',
    states: [
      { code: 'LI', name: 'Liechtenstein', cities: ['Vaduz', 'Schaan', 'Balzers', 'Triesen', 'Ruggell'] },
    ],
  },
  {
    code: 'LT',
    name: 'Lithuania',
    states: [
      { code: 'VL', name: 'Vilnius', cities: ['Vilnius', 'Trakai', 'Ukmergė', 'Širvintos'] },
      { code: 'KA', name: 'Kaunas', cities: ['Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'] },
      { code: 'KL', name: 'Klaipėda', cities: ['Klaipėda', 'Palanga', 'Neringa', 'Kretinga'] },
    ],
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    states: [
      { code: 'LU', name: 'Luxembourg', cities: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'] },
    ],
  },
  {
    code: 'MT',
    name: 'Malta',
    states: [
      { code: 'MT', name: 'Malta', cities: ['Birkirkara', 'Qormi', 'Mosta', ' Zabbar', 'San Gwann'] },
    ],
  },
  {
    code: 'MD',
    name: 'Moldova',
    states: [
      { code: 'CU', name: 'Chișinău', cities: ['Chișinău', 'Bălți', 'Tiraspol', 'Bender'] },
      { code: 'AN', name: 'Anenii Noi', cities: ['Anenii Noi', 'Chișinău', 'Căușeni'] },
    ],
  },
  {
    code: 'MC',
    name: 'Monaco',
    states: [
      { code: 'MC', name: 'Monaco', cities: ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille'] },
    ],
  },
  {
    code: 'ME',
    name: 'Montenegro',
    states: [
      { code: 'PG', name: 'Podgorica', cities: ['Podgorica', 'Danilovgrad', 'Tuzi'] },
      { code: 'NK', name: 'Nikšić', cities: ['Nikšić', 'Pljevlja', 'Cetinje'] },
      { code: 'BR', name: 'Budva', cities: ['Budva', 'Kotor', 'Tivat', 'Herceg Novi'] },
    ],
  },
  {
    code: 'NL',
    name: 'Netherlands',
    states: [
      { code: 'NH', name: 'North Holland', cities: ['Amsterdam', 'Haarlem', 'Zaanstad', 'Hoorn', 'Alkmaar'] },
      { code: 'ZH', name: 'South Holland', cities: ['Rotterdam', 'The Hague', 'Dordrecht', 'Schiedam', 'Zoetermeer'] },
      { code: 'UT', name: 'Utrecht', cities: ['Utrecht', 'Amersfoort', 'Nieuwegein', 'Zeist'] },
      { code: 'GE', name: 'Gelderland', cities: ['Nijmegen', 'Arnhem', 'Ede', 'Apeldoorn', 'Zutphen'] },
      { code: 'OV', name: 'Overijssel', cities: ['Enschede', 'Zwolle', 'Deventer', 'Hengelo'] },
      { code: 'DR', name: 'Drenthe', cities: ['Assen', 'Emmen', 'Hoogeveen', 'Coevorden'] },
      { code: 'FR', name: 'Friesland', cities: ['Leeuwarden', 'Drachten', 'Harlingen', 'Heerenveen'] },
      { code: 'GR', name: 'Groningen', cities: ['Groningen', 'Appingedam', 'Hoogezand', 'Stadskanaal'] },
      { code: 'LB', name: 'Limburg', cities: ['Maastricht', 'Venlo', 'Sittard', 'Roermond'] },
      { code: 'NB', name: 'North Brabant', cities: ['Eindhoven', 'Tilburg', 'Breda', 'Rosmalen'] },
    ],
  },
  {
    code: 'MK',
    name: 'North Macedonia',
    states: [
      { code: 'SK', name: 'Skopje', cities: ['Skopje', 'Kumanovo', 'Tetovo', 'Gostivar'] },
      { code: 'BT', name: 'Bitola', cities: ['Bitola', 'Prilep', 'Ohrid', 'Struga'] },
    ],
  },
  {
    code: 'NO',
    name: 'Norway',
    states: [
      { code: 'OS', name: 'Oslo', cities: ['Oslo'] },
      { code: 'AK', name: 'Akershus', cities: ['Bærum', 'Asker', 'Lillestrøm', 'Nittedal', 'Lørenskog'] },
      { code: 'VF', name: 'Vestfold og Telemark', cities: ['Skien', 'Porsgrunn', 'Sandefjord', 'Tønsberg'] },
      { code: 'VE', name: 'Vestland', cities: ['Bergen', 'Stavanger', 'Haugesund', 'Ålesund'] },
      { code: 'TR', name: 'Trøndelag', cities: ['Trondheim', 'Steinkjer', 'Stjørdalshalsen', 'Namsos'] },
      { code: 'OP', name: 'Innlandet', cities: ['Lillehammer', 'Hamar', 'Gjøvik', 'Elverum'] },
      { code: 'AG', name: 'Agder', cities: ['Kristiansand', 'Arendal', 'Grimstad', 'Lillesand'] },
      { code: 'MR', name: 'Møre og Romsdal', cities: ['Ålesund', 'Molde', 'Kristiansund', 'Haugesund'] },
      { code: 'RO', name: 'Rogaland', cities: ['Stavanger', 'Haugesund', 'Sola', 'Sandnes'] },
      { code: 'VK', name: 'Viken', cities: ['Oslo', 'Bærum', 'Asker', 'Lillestrøm'] },
      { code: 'FA', name: 'Finnmark', cities: ['Kirkenes', 'Alta', 'Hammerfest', 'Tromsø'] },
      { code: 'TM', name: 'Troms', cities: ['Tromsø', 'Harstad', 'Narvik', 'Bodø'] },
    ],
  },
  {
    code: 'PL',
    name: 'Poland',
    states: [
      { code: 'MZ', name: 'Masovian', cities: ['Warsaw', 'Pruszków', 'Legionowo', 'Piaseczno'] },
      { code: 'SK', name: 'Silesian', cities: ['Katowice', 'Częstochowa', 'Sosnowiec', 'Gliwice', 'Zabrze'] },
      { code: 'MA', name: 'Lesser Poland', cities: ['Kraków', 'Tarnów', 'Nowy Sącz', 'Oświęcim'] },
      { code: 'DN', name: 'Greater Poland', cities: ['Poznań', 'Kalisz', 'Konin', 'Piła', 'Ostrów Wielkopolski'] },
      { code: 'WP', name: 'West Pomeranian', cities: ['Szczecin', 'Koszalin', 'Stargard', 'Kołobrzeg'] },
      { code: 'PD', name: 'Podlaskie', cities: ['Białystok', 'Łomża', 'Suwałki', 'Bielsk Podlaski'] },
      { code: 'PM', name: 'Pomeranian', cities: ['Gdańsk', 'Gdynia', 'Sopot', 'Rumia', 'Starogard Gdański'] },
      { code: 'DS', name: 'Lower Silesian', cities: ['Wrocław', 'Wałbrzych', 'Legnica', 'Jelenia Góra'] },
      { code: 'KP', name: 'Kuyavian-Pomeranian', cities: ['Bydgoszcz', 'Toruń', 'Włocławek', 'Grudziądz'] },
      { code: 'LD', name: 'Łódź', cities: ['Łódź', 'Piotrków Trybunalski', 'Pabianice', 'Tomaszów Mazowiecki'] },
      { code: 'LB', name: 'Lublin', cities: ['Lublin', 'Chełm', 'Zamość', 'Biała Podlaska'] },
      { code: 'OP', name: 'Opole', cities: ['Opole', 'Kędzierzyn-Koźle', 'Nysa', 'Brzeg'] },
      { code: 'PO', name: 'Subcarpathian', cities: ['Rzeszów', 'Przemyśl', 'Stalowa Wola', 'Tarnobrzeg'] },
      { code: 'SL', name: 'Świętokrzyskie', cities: ['Kielce', 'Ostrowiec Świętokrzyski', 'Starachowice'] },
      { code: 'WZ', name: 'Warmian-Masurian', cities: ['Olsztyn', 'Elbląg', 'Ełk', 'Ostrołęka'] },
      { code: 'ZD', name: 'Lubusz', cities: ['Gorzów Wielkopolski', 'Zielona Góra', 'Nowa Sól'] },
    ],
  },
  {
    code: 'PT',
    name: 'Portugal',
    states: [
      { code: 'LI', name: 'Lisbon', cities: ['Lisbon', 'Sintra', 'Amadora', 'Barreiro', 'Matosinhos'] },
      { code: 'PO', name: 'Porto', cities: ['Porto', 'Vila Nova de Gaia', 'Braga', 'Maia', 'Gondomar'] },
      { code: 'BR', name: 'Braga', cities: ['Braga', 'Barcelos', 'Guimarães', 'Fafe'] },
      { code: 'LE', name: 'Leiria', cities: ['Leiria', 'Caldas da Rainha', 'Pombal', 'Marinha Grande'] },
      { code: 'CO', name: 'Coimbra', cities: ['Coimbra', 'Figueira da Foz', 'Cantanhede'] },
      { code: 'AV', name: 'Aveiro', cities: ['Aveiro', 'Ílhavo', 'Ovar', 'Estarreja'] },
      { code: 'FAR', name: 'Faro', cities: ['Faro', 'Portimão', 'Lagos', 'Tavira', 'Silves'] },
      { code: 'VIS', name: 'Viseu', cities: ['Viseu', 'Lamego', 'São João da Pesqueira'] },
      { code: 'VIA', name: 'Viana do Castelo', cities: ['Viana do Castelo', 'Vila Nova de Cerveira', 'Caminha'] },
      { code: 'SET', name: 'Santarém', cities: ['Santarém', 'Abrantes', 'Torres Novas', 'Ourém'] },
    ],
  },
  {
    code: 'RO',
    name: 'Romania',
    states: [
      { code: 'B', name: 'Bucharest', cities: ['Bucharest', 'Sector 1', 'Sector 2', 'Sector 3', 'Sector 4', 'Sector 5', 'Sector 6'] },
      { code: 'CJ', name: 'Cluj', cities: ['Cluj-Napoca', 'Turda', 'Dej', 'Câmpia Turzii'] },
      { code: 'IS', name: 'Iași', cities: ['Iași', 'Pașcani', 'Hârlău', 'Rădăuți'] },
      { code: 'TM', name: 'Timiș', cities: ['Timișoara', 'Lugoj', 'Reșița', 'Arad'] },
      { code: 'CT', name: 'Constanța', cities: ['Constanța', 'Cta', 'Mangalia', 'Medgidia'] },
      { code: 'BV', name: 'Brașov', cities: ['Brașov', 'Sibiu', 'Sighișoara', 'Făgăraș'] },
      { code: 'GR', name: 'Galați', cities: ['Galați', 'Brăila', 'Focșani', 'Buzău'] },
      { code: 'PH', name: 'Prahova', cities: ['Ploiești', 'Câmpina', 'Slănic', 'Băicoi'] },
      { code: 'HD', name: 'Hunedoara', cities: ['Hunedoara', 'Deva', 'Lupeni', 'Petroșani'] },
      { code: 'CJ', name: 'Constanța', cities: ['Constanța', 'Mangalia', 'Năvodari'] },
    ],
  },
  {
    code: 'RS',
    name: 'Serbia',
    states: [
      { code: 'BG', name: 'Belgrade', cities: ['Belgrade', 'Novi Sad', 'Kragujevac', 'Niš'] },
      { code: 'VO', name: 'Vojvodina', cities: ['Novi Sad', 'Subotica', 'Sombor', 'Kikinda'] },
      { code: 'SUM', name: 'Šumadija', cities: ['Kragujevac', 'Aranđelovac', 'Batočina'] },
      { code: 'MOR', name: 'Moravica', cities: ['Čačak', 'Gornji Milanovac', 'Lučani'] },
      { code: 'ZLA', name: 'Zlatibor', cities: ['Užice', 'Požega', 'Prijepolje', 'Sjenica'] },
      { code: 'MAC', name: 'Mačva', cities: ['Šabac', 'Loznica', 'Valjevo'] },
      { code: 'NI', name: 'Niš', cities: ['Niš', 'Leskovac', 'Vranje', 'Pirot'] },
      { code: 'RA', name: 'Raška', cities: ['Kraljevo', 'Novi Pazar', 'Vrnjacka Banja'] },
    ],
  },
  {
    code: 'SK',
    name: 'Slovakia',
    states: [
      { code: 'BL', name: 'Bratislava', cities: ['Bratislava', 'Pezinok', 'Malacky', 'Senec'] },
      { code: 'KI', name: 'Košice', cities: ['Košice', 'Michalovce', 'Spišská Nová Ves'] },
      { code: 'BB', name: 'Banská Bystrica', cities: ['Banská Bystrica', 'Zvolen', 'Lučenec'] },
      { code: 'NR', name: 'Nitra', cities: ['Nitra', 'Nové Zámky', 'Komárno', 'Levice'] },
      { code: 'TN', name: 'Trenčín', cities: ['Trenčín', 'Prievidza', 'Považská Bystrica'] },
      { code: 'TT', name: 'Trnava', cities: ['Trnava', 'Piešťany', 'Galanta', 'Hlohovec'] },
      { code: 'ZM', name: 'Žilina', cities: ['Žilina', 'Martin', 'Liptovský Mikuláš', 'Čadca'] },
      { code: 'PO', name: 'Prešov', cities: ['Prešov', 'Bardejov', 'Humenné', 'Snina'] },
    ],
  },
  {
    code: 'SI',
    name: 'Slovenia',
    states: [
      { code: 'LJ', name: 'Ljubljana', cities: ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper'] },
      { code: 'MB', name: 'Maribor', cities: ['Maribor', 'Ptuj', 'Slovenska Bistrica'] },
      { code: 'CE', name: 'Celje', cities: ['Celje', 'Velenje', 'Trbovlje'] },
      { code: 'KR', name: 'Kranj', cities: ['Kranj', 'Jesenice', 'Radovljica'] },
    ],
  },
  {
    code: 'ES',
    name: 'Spain',
    states: [
      { code: 'MD', name: 'Madrid', cities: ['Madrid', 'Parla', 'Fuenlabrada', 'Móstoles', 'Alcalá de Henares'] },
      { code: 'CT', name: 'Catalonia', cities: ['Barcelona', "L'Hospitalet", 'Terrassa', 'Badalona', 'Sabadell'] },
      { code: 'VC', name: 'Valencia', cities: ['Valencia', 'Alicante', 'Elche', 'Castellón', 'Sagunto'] },
      { code: 'AN', name: 'Andalusia', cities: ['Seville', 'Malaga', 'Córdoba', 'Granada', 'Jerez', 'Cadiz'] },
      { code: 'PV', name: 'Basque Country', cities: ['Bilbao', 'Vitoria-Gasteiz', 'San Sebastián', 'Getxo'] },
      { code: 'GA', name: 'Galicia', cities: ['Vigo', 'A Coruña', 'Santiago de Compostela', 'Lugo'] },
      { code: 'CL', name: 'Castile and León', cities: ['Valladolid', 'Burgos', 'León', 'Salamanca', 'Palencia'] },
      { code: 'CM', name: 'Castile-La Mancha', cities: ['Toledo', 'Albacete', 'Ciudad Real', 'Cuenca'] },
      { code: 'MC', name: 'Murcia', cities: ['Murcia', 'Cartagena', 'Lorca'] },
      { code: 'AR', name: 'Aragon', cities: ['Zaragoza', 'Huesca', 'Teruel', 'Calatayud'] },
      { code: 'EX', name: 'Extremadura', cities: ['Badajoz', 'Cáceres', 'Mérida', 'Plasencia'] },
      { code: 'AS', name: 'Asturias', cities: ['Oviedo', 'Gijón', 'Avilés', 'Siero'] },
      { code: 'NA', name: 'Navarre', cities: ['Pamplona', 'Tudela', 'Burlada', 'Tafalla'] },
      { code: 'RI', name: 'La Rioja', cities: ['Logroño', 'Calahorra', 'Haro', 'Lardero'] },
      { code: 'CB', name: 'Cantabria', cities: ['Santander', 'Torrelavega', 'Camargo', 'Castro Urdiales'] },
    ],
  },
  {
    code: 'SE',
    name: 'Sweden',
    states: [
      { code: 'ST', name: 'Stockholm', cities: ['Stockholm', 'Södertälje', 'Tumba', 'Upplands Väsby', 'Lidingö'] },
      { code: 'GD', name: 'Gothenburg', cities: ['Gothenburg', 'Mölndal', 'Partille', 'Kungsbacka'] },
      { code: 'MU', name: 'Malmö', cities: ['Malmö', 'Lund', 'Helsingborg', 'Landskrona'] },
      { code: 'UP', name: 'Uppsala', cities: ['Uppsala', 'Enköping', 'Tierp'] },
      { code: 'OR', name: 'Örebro', cities: ['Örebro', 'Karlskoga', 'Kumla', 'Lindesberg'] },
      { code: 'VR', name: 'Västra Götaland', cities: ['Gothenburg', 'Uddevalla', 'Vänersborg', 'Lysekil'] },
      { code: 'SN', name: 'Södermanland', cities: ['Nyköping', 'Eskilstuna', 'Katrineholm', 'Strängnäs'] },
      { code: 'LK', name: 'Linköping', cities: ['Linköping', 'Norrköping', 'Motala', 'Mjölby'] },
      { code: 'JO', name: 'Jönköping', cities: ['Jönköping', 'Växjö', 'Nässjö', 'Eksjö'] },
      { code: 'BL', name: 'Blekinge', cities: ['Karlskrona', 'Ronneby', 'Karlshamn', 'Sölvesborg'] },
      { code: 'HA', name: 'Halland', cities: ['Halmstad', 'Falkenberg', 'Varberg', 'Kungsbacka'] },
      { code: 'GA', name: 'Gävleborg', cities: ['Gävle', 'Sandviken', 'Bollnäs', 'Hudiksvall'] },
      { code: 'VB', name: 'Västerbotten', cities: ['Umeå', 'Skellefteå', 'Lycksele', 'Holmsund'] },
      { code: 'NO', name: 'Norrbotten', cities: ['Luleå', 'Piteå', 'Boden', 'Kiruna', 'Gällivare'] },
      { code: 'DI', name: 'Dalarna', cities: ['Falun', 'Borlänge', 'Avesta', 'Ludvika', 'Mora'] },
    ],
  },
  {
    code: 'CH',
    name: 'Switzerland',
    states: [
      { code: 'ZH', name: 'Zurich', cities: ['Zurich', 'Winterthur', 'Uster', 'Dietikon', 'Wädenswil'] },
      { code: 'GE', name: 'Geneva', cities: ['Geneva', 'Carouge', 'Vernier', 'Lancy', 'Meyrin'] },
      { code: 'BE', name: 'Bern', cities: ['Bern', 'Biel/Bienne', 'Thun', 'Köniz', 'Steffisburg'] },
      { code: 'VD', name: 'Vaud', cities: ['Lausanne', 'Yverdon-les-Bains', 'Montreux', 'Renens', 'Nyon'] },
      { code: 'BS', name: 'Basel-Stadt', cities: ['Basel', 'Riehen', 'Bettingen'] },
      { code: 'BL', name: 'Basel-Landschaft', cities: ['Liestal', 'Binningen', 'Bottmingen', 'Münchenstein'] },
      { code: 'AG', name: 'Aargau', cities: ['Aarau', 'Baden', 'Wohlen', 'Zofingen', 'Lenzburg'] },
      { code: 'LU', name: 'Lucerne', cities: ['Lucerne', 'Emmen', 'Kriens', 'Horw', 'Ebikon'] },
      { code: 'SG', name: 'St. Gallen', cities: ['St. Gallen', 'Rapperswil-Jona', 'Wil', 'Gossau'] },
      { code: 'TI', name: 'Ticino', cities: ['Lugano', 'Bellinzona', 'Locarno', 'Chiasso'] },
      { code: 'GR', name: 'Graubünden', cities: ['Chur', 'Davos', 'St. Moritz', 'Arosa'] },
      { code: 'VS', name: 'Valais', cities: ['Sion', 'Brig', 'Crans-Montana', 'Martigny'] },
      { code: 'NE', name: 'Neuchâtel', cities: ['Neuchâtel', 'La Chaux-de-Fonds', 'Le Locle'] },
      { code: 'FR', name: 'Fribourg', cities: ['Fribourg', 'Bulle', 'Estavayer-le-Lac', 'Murten'] },
    ],
  },
  {
    code: 'UA',
    name: 'Ukraine',
    states: [
      { code: 'KV', name: 'Kyiv', cities: ['Kyiv', 'Brovary', 'Bucha', 'Irpin', 'Vasylkiv'] },
      { code: 'OD', name: 'Odesa', cities: ['Odesa', 'Mykolaiv', 'Kherson', 'Izmail'] },
      { code: 'LV', name: 'Lviv', cities: ['Lviv', 'Drogobych', 'Chervonohrad', 'Stryi'] },
      { code: 'KH', name: 'Kharkiv', cities: ['Kharkiv', 'Lozova', 'Izyum', 'Chuhuiv'] },
      { code: 'DN', name: 'Dnipro', cities: ['Dnipro', 'Kropyvnytskyi', 'Kryvyi Rih', 'Nikopol'] },
      { code: 'ZP', name: 'Zaporizhzhia', cities: ['Zaporizhzhia', 'Melitopol', 'Berdyansk', 'Enerhodar'] },
      { code: 'VN', name: 'Vinnytsia', cities: ['Vinnytsia', 'Zhytomyr', 'Berdychiv', 'Khmelnytskyi'] },
      { code: 'IF', name: 'Ivano-Frankivsk', cities: ['Ivano-Frankivsk', 'Kalush', 'Kolomyia', 'Nadvirna'] },
      { code: 'CF', name: 'Cherkasy', cities: ['Cherkasy', 'Uman', 'Smila', 'Zolotonosha'] },
      { code: 'CK', name: 'Chernihiv', cities: ['Chernihiv', 'Nizhyn', 'Pryluky', 'Bakhmach'] },
      { code: 'CV', name: 'Chernivtsi', cities: ['Chernivtsi', 'Storozhynets', 'Staryi Sambir'] },
      { code: 'SM', name: 'Sumy', cities: ['Sumy', 'Konotop', 'Shostka', 'Romny'] },
      { code: 'PO', name: 'Poltava', cities: ['Poltava', 'Kremenchuk', 'Lubny', 'Myrhorod'] },
      { code: 'TE', name: 'Ternopil', cities: ['Ternopil', 'Kremenets', 'Terebovlia', 'Chortkiv'] },
      { code: 'ZT', name: 'Zytomyr', cities: ['Zytomyr', 'Berdychiv', 'Korosten', 'Novohrad-Volynskyi'] },
      { code: 'HM', name: 'Khmelnytskyi', cities: ['Khmelnytskyi', 'Kamianets-Podilskyi', 'Shepetivka'] },
      { code: 'LU', name: 'Luhansk', cities: ['Sievierodonetsk', 'Luhansk', 'Alchevsk', 'Lysychansk'] },
    ],
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    states: [
      { code: 'EN', name: 'England', cities: ['London', 'Birmingham', 'Manchester', 'Leeds', 'Liverpool', 'Sheffield', 'Bristol', 'Newcastle', 'Nottingham', 'Leicester', 'Southampton', 'Brighton', 'Bournemouth', 'Oxford', 'Cambridge'] },
      { code: 'SC', name: 'Scotland', cities: ['Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee', 'Inverness', 'Stirling'] },
      { code: 'WA', name: 'Wales', cities: ['Cardiff', 'Swansea', 'Newport', 'Wrexham', 'Barry'] },
      { code: 'NI', name: 'Northern Ireland', cities: ['Belfast', 'Derry', 'Lisburn', 'Newry', 'Armagh'] },
    ],
  },

  // ============ ASIA (Developed Countries Only) ============
  {
    code: 'JP',
    name: 'Japan',
    states: [
      { code: 'TK', name: 'Tokyo', cities: ['Tokyo', 'Hachioji', 'Machida', 'Suginami', 'Shinagawa', 'Shibuya', 'Shinjuku'] },
      { code: 'OS', name: 'Osaka', cities: ['Osaka', 'Sakai', 'Higashiosaka', 'Toyonaka', 'Suita'] },
      { code: 'KT', name: 'Kanagawa', cities: ['Yokohama', 'Kawasaki', 'Sagamihara', 'Fujisawa', 'Miura'] },
      { code: 'AJ', name: 'Aichi', cities: ['Nagoya', 'Toyota', 'Okazaki', 'Toyohashi', 'Kasugai'] },
      { code: 'HT', name: 'Hokkaido', cities: ['Sapporo', 'Asahikawa', 'Hakodate', 'Otaru', 'Kushiro'] },
      { code: 'SG', name: 'Saitama', cities: ['Saitama', 'Kawaguchi', 'Kawagoe', 'Tokorozawa', 'Niiza'] },
      { code: 'KB', name: 'Kyoto', cities: ['Kyoto', 'Uji', 'Kawagoe', 'Kameoka'] },
      { code: 'FS', name: 'Fukuoka', cities: ['Fukuoka', 'Kitakyushu', 'Kurume', 'Iizuka'] },
      { code: 'HI', name: 'Hiroshima', cities: ['Hiroshima', 'Fukuyama', 'Kure', 'Higashihiroshima'] },
      { code: 'NG', name: 'Nara', cities: ['Nara', 'Yamatokoriyama', 'Yoshino', 'Ikoma'] },
      { code: 'SH', name: 'Shizuoka', cities: ['Shizuoka', 'Hamamatsu', 'Fuji', 'Numazu', 'Yaizu'] },
      { code: 'KW', name: 'Kagawa', cities: ['Takamatsu', 'Matsuyama', 'Imabari', 'Uwajima'] },
      { code: 'IS', name: 'Ishikawa', cities: ['Kanazawa', 'Toyama', 'Kashiwazaki', 'Takaoka', 'Fukui'] },
      { code: 'GO', name: 'Gifu', cities: ['Gifu', 'Ogaki', 'Takayama', 'Seki', 'Tajimi'] },
      { code: 'NM', name: 'Nagano', cities: ['Nagano', 'Matsumoto', 'Sakaki', 'Suwa', 'Ueda'] },
      { code: 'OA', name: 'Oita', cities: ['Oita', 'Beppu', 'Nakatsu', 'Hita'] },
      { code: 'KG', name: 'Kagoshima', cities: ['Kagoshima', 'Kirishima', 'Satsumasendai'] },
      { code: 'YG', name: 'Yamanashi', cities: ['Kofu', 'Fujiyoshida', 'Yamanashi', 'Kai'] },
      { code: 'TO', name: 'Tochigi', cities: ['Utsunomiya', 'Ashikaga', 'Kawagoe', 'Nasushiobara'] },
      { code: 'IB', name: 'Ibaraki', cities: ['Mito', 'Tsukuba', 'Hitachinaka', 'Kashima'] },
      { code: 'GU', name: 'Gunma', cities: ['Maebashi', 'Takasaki', 'Kiryu', 'Isesaki', 'Ōta'] },
      { code: 'SI', name: 'Shiga', cities: ['Otsu', 'Kusatsu', 'Nagahama', 'Hikone'] },
      { code: 'YM', name: 'Yamaguchi', cities: ['Yamaguchi', 'Shunan', 'Ube', 'Hagi', 'Hikari'] },
      { code: 'FK', name: 'Fukui', cities: ['Fukui', 'Tsuruga', 'Sabae', 'Obama'] },
      { code: 'TE', name: 'Tottori', cities: ['Tottori', 'Yonago', 'Sakaiminato', 'Kurayoshi'] },
    ],
  },
  {
    code: 'KR',
    name: 'South Korea',
    states: [
      { code: 'SE', name: 'Seoul', cities: ['Seoul', 'Gangnam', 'Gangbuk', 'Mapo', 'Jung', 'Yongsan'] },
      { code: 'KG', name: 'Gyeonggi', cities: ['Suwon', 'Seongnam', 'Goyang', 'Yongin', 'Bucheon', 'Ansan'] },
      { code: 'BS', name: 'Busan', cities: ['Busan', 'Gijang', 'Gimhae', 'Ulsan', 'Changwon'] },
      { code: 'IC', name: 'Incheon', cities: ['Incheon', 'Jung-gu', 'Bupyeong', 'Gyeyang'] },
      { code: 'DJ', name: 'Daejeon', cities: ['Daejeon', 'Jung-gu', 'Seowon', 'Yuseong'] },
      { code: 'GG', name: 'Gwangju', cities: ['Gwangju', 'Nam-gu', 'Buk-gu', 'Gwangsan'] },
      { code: 'UL', name: 'Ulsan', cities: ['Ulsan', 'Jung-gu', 'Nam-gu', 'Dong-gu', 'Buk-gu'] },
      { code: 'SJ', name: 'Sejong', cities: ['Sejong City', 'Jeonju', 'Gwangju', 'Daejeon'] },
      { code: 'CB', name: 'North Chungcheong', cities: ['Cheongju', 'Jincheon', 'Okcheon', 'Boeun'] },
      { code: 'CN', name: 'South Chungcheong', cities: ['Cheonan', 'Asan', 'Soscal', 'Gyeryong'] },
      { code: 'JB', name: 'North Jeolla', cities: ['Jeonju', 'Gimje', 'Namwon', 'Iksan'] },
      { code: 'JN', name: 'South Jeolla', cities: ['Gwangju', 'Naju', 'Yeosu', 'Suncheon'] },
      { code: 'KB', name: 'North Gyeongsang', cities: ['Daegu', 'Gyeongju', 'Pohang', 'Gyeongsan'] },
      { code: 'KN', name: 'South Gyeongsang', cities: ['Changwon', 'Masan', 'Jinju', 'Tongyoung'] },
      { code: 'GW', name: 'Gangwon', cities: ['Chuncheon', 'Wonju', 'Gangneung', 'Sokcho'] },
    ],
  },
  {
    code: 'SG',
    name: 'Singapore',
    states: [
      { code: 'SG', name: 'Singapore', cities: ['Singapore', 'Orchard', 'Marina Bay', 'Sentosa'] },
    ],
  },
  {
    code: 'TW',
    name: '中国台湾',
    states: [
      { code: 'TPE', name: 'Taipei', cities: ['Taipei', 'New Taipei', 'Taoyuan', 'Keelung', 'Yilan'] },
      { code: 'TNN', name: 'Tainan', cities: ['Tainan', 'Anping', 'Anshan', 'Xinhua'] },
      { code: 'TXG', name: 'Taichung', cities: ['Taichung', 'Fengyuan', 'Dajia', 'Qingshui'] },
      { code: 'KHH', name: 'Kaohsiung', cities: ['Kaohsiung', 'Fengshan', 'Zuoying', 'Qianzhen'] },
      { code: 'HSZ', name: 'Hsinchu', cities: ['Hsinchu', 'Zhudong', 'Xinfeng', 'Guangfu'] },
    ],
  },
  {
    code: 'HK',
    name: '中国香港',
    states: [
      { code: 'HK', name: '中国香港', cities: ['Hong Kong Island', 'Kowloon', 'New Territories'] },
    ],
  },
  {
    code: 'MO',
    name: '中国澳门',
    states: [
      { code: 'MO', name: '中国澳门', cities: ['Macau Peninsula', 'Taipa', 'Coloane'] },
    ],
  },
  {
    code: 'MY',
    name: 'Malaysia',
    states: [
      { code: 'KL', name: 'Kuala Lumpur', cities: ['Kuala Lumpur', 'Petaling Jaya', 'Shah Alam', 'Klang', 'Subang Jaya'] },
      { code: 'JH', name: 'Johor', cities: ['Johor Bahru', 'Skudai', 'Pasir Gudang', 'Kulai', 'Senai'] },
      { code: 'PN', name: 'Penang', cities: ['George Town', 'Butterworth', 'Seberang Perai'] },
      { code: 'SL', name: 'Selangor', cities: ['Shah Alam', 'Petaling Jaya', 'Klang', 'Subang Jaya', 'Ampang'] },
      { code: 'KH', name: 'Kedah', cities: ['Alor Setar', 'Sungai Petani', 'Kulim', 'Langkawi'] },
      { code: 'KN', name: 'Kelantan', cities: ['Kota Bharu', 'Tumpat', 'Kuala Krai', 'Tanah Merah'] },
      { code: 'TR', name: 'Terengganu', cities: ['Kuala Terengganu', 'Dungun', 'Besut', 'Marang'] },
      { code: 'PH', name: 'Pahang', cities: ['Kuantan', 'Temerloh', 'Bentong', 'Rompin'] },
      { code: 'SR', name: 'Sarawak', cities: ['Kuching', 'Sibu', 'Miri', 'Bintulu', 'Sri Aman'] },
      { code: 'SB', name: 'Sabah', cities: ['Kota Kinabalu', 'Sandakan', 'Tawau', 'Keningau'] },
      { code: 'NS', name: 'Negeri Sembilan', cities: ['Seremban', 'Port Dickson', 'Nilai'] },
      { code: 'ML', name: 'Malacca', cities: ['Malacca City', 'Alor Gajah', 'Jasin'] },
      { code: 'PG', name: 'Perak', cities: ['Ipoh', 'Taiping', 'Manjung', 'Kinta'] },
      { code: 'PK', name: 'Perlis', cities: ['Kangar', 'Arau', 'Padang Besar'] },
    ],
  },
  {
    code: 'TH',
    name: 'Thailand',
    states: [
      { code: 'BKK', name: 'Bangkok', cities: ['Bangkok', 'Nonthaburi', 'Pathum Thani', 'Samut Prakan'] },
      { code: 'CH', name: 'Chiang Mai', cities: ['Chiang Mai', 'Chiang Rai', 'Pai', 'Mae Sariang'] },
      { code: 'PT', name: 'Phuket', cities: ['Phuket', 'Patong', 'Karon', 'Kata'] },
      { code: 'SK', name: 'Surat Thani', cities: ['Surat Thani', 'Koh Samui', 'Koh Phangan', 'Chaiya'] },
      { code: 'CR', name: 'Chonburi', cities: ['Chonburi', 'Pattaya', 'Bang Saen', 'Sri Racha'] },
      { code: 'RI', name: 'Rayong', cities: ['Rayong', 'Bang Bo', 'Klaeng', 'Ban Khai'] },
      { code: 'CN', name: 'Chiang Rai', cities: ['Chiang Rai', 'Chiang Saen', 'Mae Sai'] },
      { code: 'NPT', name: 'Nakhon Pathom', cities: ['Nakhon Pathom', 'Sam Phran', 'Nakhon Chaisri'] },
      { code: 'PKN', name: 'Prachuap Khiri Khan', cities: ['Prachuap Khiri Khan', 'Hua Hin', 'Pranburi'] },
    ],
  },
  {
    code: 'VN',
    name: 'Vietnam',
    states: [
      { code: 'HN', name: 'Hanoi', cities: ['Hanoi', 'Ha Dong', 'Long Biên', 'Cau Giay', 'Nam Tu Liem'] },
      { code: 'HCM', name: 'Ho Chi Minh City', cities: ['Ho Chi Minh City', 'Thu Duc', 'District 1', 'District 7'] },
      { code: 'DN', name: 'Da Nang', cities: ['Da Nang', 'Hai Chau', 'Thanh Khe', 'Son Tra'] },
      { code: 'HP', name: 'Haiphong', cities: ['Haiphong', 'Hong Bang', 'Le Chan', 'Ngo Quyen'] },
      { code: 'CT', name: 'Can Tho', cities: ['Can Tho', 'Ninh Kieu', 'Binh Thuy'] },
      { code: 'HUE', name: 'Hue', cities: ['Hue', 'Huong Thuy', 'Huong Tra'] },
      { code: 'QN', name: 'Quang Ninh', cities: ['Halong', 'Uong Bi', 'Hong Gai'] },
      { code: 'ND', name: 'Nam Dinh', cities: ['Nam Dinh', 'Hai Duong', 'Thai Binh'] },
      { code: 'TH', name: 'Thanh Hoa', cities: ['Thanh Hoa', 'Bim Son', 'Sam Son'] },
      { code: 'NT', name: 'Nha Trang', cities: ['Nha Trang', 'Ninh Hoa', 'Cam Ranh'] },
      { code: 'GL', name: 'Gia Lai', cities: ['Pleiku', 'Tam Ky', 'Kon Tum'] },
      { code: 'LD', name: 'Lam Dong', cities: ['Da Lat', 'Bao Loc', 'Di Linh'] },
    ],
  },
  {
    code: 'PH',
    name: 'Philippines',
    states: [
      { code: 'MM', name: 'Metro Manila', cities: ['Manila', 'Quezon City', 'Makati', 'Caloocan', 'Taguig'] },
      { code: 'CE', name: 'Cebu', cities: ['Cebu City', 'Mandaue', 'Lapu-Lapu'] },
      { code: 'DV', name: 'Davao', cities: ['Davao City', 'Digos', 'Tagum'] },
      { code: 'BT', name: 'Batangas', cities: ['Batangas City', 'Lipa', 'Tanauan', 'Santo Tomas'] },
      { code: 'CV', name: 'Cavite', cities: ['Imus', 'Dasmariñas', 'Bacoor', 'Tagaytay'] },
      { code: 'LG', name: 'Laguna', cities: ['Santa Rosa', 'Biñan', 'San Pedro', 'Calamba'] },
      { code: 'RI', name: 'Rizal', cities: ['Antipolo', 'Cainta', 'Taytay', 'Binangonan'] },
      { code: 'PN', name: 'Pampanga', cities: ['Angeles City', 'San Fernando', 'Mabalacat'] },
      { code: 'ZL', name: 'Zamboanga del Sur', cities: ['Zamboanga City', 'Pagadian', 'Dipolog'] },
      { code: 'IC', name: 'Iligan', cities: ['Iligan', 'Marawi', 'Lanao del Norte'] },
    ],
  },
  {
    code: 'ID',
    name: 'Indonesia',
    states: [
      { code: 'JK', name: 'Jakarta', cities: ['Jakarta', 'South Jakarta', 'West Jakarta', 'East Jakarta', 'North Jakarta'] },
      { code: 'JR', name: 'East Java', cities: ['Surabaya', 'Malang', 'Kediri', 'Mojokerto'] },
      { code: 'BD', name: 'Bali', cities: ['Denpasar', 'Badung', 'Gianyar', 'Tabanan'] },
      { code: 'JB', name: 'West Java', cities: ['Bandung', 'Bekasi', 'Depok', 'Cirebon', 'Bogor'] },
      { code: 'JT', name: 'Central Java', cities: ['Semarang', 'Solo', 'Salatiga', 'Kudus'] },
      { code: 'JY', name: 'Yogyakarta', cities: ['Yogyakarta', 'Sleman', 'Bantul', 'Wonosari'] },
      { code: 'KT', name: 'Kalimantan', cities: ['Balikpapan', 'Samarinda', 'Pontianak', 'Banjarmasin'] },
      { code: 'SB', name: 'Sumatera', cities: ['Medan', 'Palembang', 'Padang', 'Pekanbaru', 'Batam'] },
      { code: 'SW', name: 'Sulawesi', cities: ['Makassar', 'Manado', 'Kendari', 'Palu'] },
    ],
  },
  {
    code: 'IN',
    name: 'India',
    states: [
      { code: 'DL', name: 'Delhi', cities: ['New Delhi', 'Delhi', 'Gurgaon', 'Noida', 'Faridabad', 'Ghaziabad'] },
      { code: 'MH', name: 'Maharashtra', cities: ['Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik', 'Aurangabad'] },
      { code: 'KA', name: 'Karnataka', cities: ['Bangalore', 'Mysore', 'Hubli', 'Mangalore', 'Belgaum', 'Mysore'] },
      { code: 'TN', name: 'Tamil Nadu', cities: ['Chennai', 'Coimbatore', 'Madurai', 'Trichy', 'Salem', 'Vellore'] },
      { code: 'AP', name: 'Andhra Pradesh', cities: ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Tirupati', 'Nellore'] },
      { code: 'TG', name: 'Telangana', cities: ['Hyderabad', 'Secunderabad', 'Warangal', 'Karimnagar'] },
      { code: 'GJ', name: 'Gujarat', cities: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar'] },
      { code: 'RJ', name: 'Rajasthan', cities: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Ajmer'] },
      { code: 'UP', name: 'Uttar Pradesh', cities: ['Lucknow', 'Kanpur', 'Varanasi', 'Agra', 'Meerut', 'Allahabad'] },
      { code: 'MP', name: 'Madhya Pradesh', cities: ['Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain'] },
      { code: 'WB', name: 'West Bengal', cities: ['Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri'] },
      { code: 'PB', name: 'Punjab', cities: ['Chandigarh', 'Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala'] },
      { code: 'HR', name: 'Haryana', cities: ['Gurgaon', 'Faridabad', 'Panipat', 'Karnal', 'Rohtak'] },
      { code: 'KE', name: 'Kerala', cities: ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur', 'Kollam'] },
      { code: 'OR', name: 'Odisha', cities: ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur'] },
      { code: 'CT', name: 'Chhattisgarh', cities: ['Raipur', 'Bhilai', 'Bilaspur', 'Durg'] },
      { code: 'JK', name: 'Jammu and Kashmir', cities: ['Srinagar', 'Jammu', 'Anantnag', 'Leh'] },
    ],
  },
  {
    code: 'PK',
    name: 'Pakistan',
    states: [
      { code: 'IS', name: 'Islamabad', cities: ['Islamabad', 'Rawalpindi'] },
      { code: 'PB', name: 'Punjab', cities: ['Lahore', 'Faisalabad', 'Rawalpindi', 'Multan', 'Sargodha'] },
      { code: 'SN', name: 'Sindh', cities: ['Karachi', 'Hyderabad', 'Sukkur', 'Larkana'] },
      { code: 'KP', name: 'Khyber Pakhtunkhwa', cities: ['Peshawar', 'Mardan', 'Abbottabad', 'Swat', 'Kohat'] },
      { code: 'BL', name: 'Balochistan', cities: ['Quetta', 'Gwadar', 'Sibi', 'Kalat', 'Turbat'] },
      { code: 'GB', name: 'Gilgit-Baltistan', cities: ['Gilgit', 'Skardu', 'Hunza', 'Ghizer'] },
    ],
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    states: [
      { code: 'DH', name: 'Dhaka', cities: ['Dhaka', 'Gazipur', 'Narayanganj', 'Tangail'] },
      { code: 'CT', name: 'Chittagong', cities: ['Chittagong', 'Cox\'s Bazar', 'Rangamati', 'Bandarban'] },
      { code: 'SR', name: 'Sylhet', cities: ['Sylhet', 'Moulvibazar', 'Habiganj', 'Sunamganj'] },
      { code: 'KH', name: 'Khulna', cities: ['Khulna', 'Jessore', 'Satkhira', 'Bagerhat'] },
      { code: 'RJ', name: 'Rajshahi', cities: ['Rajshahi', 'Bogra', 'Pabna', 'Naogaon'] },
      { code: 'MY', name: 'Mymensingh', cities: ['Mymensingh', 'Jamalpur', 'Sherpur', 'Netrokona'] },
    ],
  },

  // ============ OCEANIA (Major Countries Only) ============
  {
    code: 'AU',
    name: 'Australia',
    states: [
      { code: 'NSW', name: 'New South Wales', cities: ['Sydney', 'Newcastle', 'Wollongong', 'Central Coast', 'Parramatta'] },
      { code: 'VIC', name: 'Victoria', cities: ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo', 'Melton'] },
      { code: 'QLD', name: 'Queensland', cities: ['Brisbane', 'Gold Coast', 'Sunshine Coast', 'Townsville', 'Cairns'] },
      { code: 'WA', name: 'Western Australia', cities: ['Perth', 'Fremantle', 'Rockingham', 'Mandurah', 'Kalgoorlie'] },
      { code: 'SA', name: 'South Australia', cities: ['Adelaide', 'Mount Gambier', 'Port Adelaide', 'Salisbury'] },
      { code: 'TAS', name: 'Tasmania', cities: ['Hobart', 'Launceston', 'Devonport', 'Burnie'] },
      { code: 'ACT', name: 'Australian Capital Territory', cities: ['Canberra', 'Queanbeyan'] },
      { code: 'NT', name: 'Northern Territory', cities: ['Darwin', 'Alice Springs', 'Palmerston', 'Katherine'] },
    ],
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    states: [
      { code: 'AUK', name: 'Auckland', cities: ['Auckland', 'North Shore', 'Waitakere', 'Manukau', 'Papakura'] },
      { code: 'WGN', name: 'Wellington', cities: ['Wellington', 'Lower Hutt', 'Upper Hutt', 'Porirua', 'Masterton'] },
      { code: 'CAN', name: 'Canterbury', cities: ['Christchurch', 'Ashburton', 'Timaru', 'Greymouth'] },
      { code: 'OTA', name: 'Otago', cities: ['Dunedin', 'Queenstown', 'Alexandra', ' Wanaka'] },
      { code: 'WAI', name: 'Waikato', cities: ['Hamilton', 'Taupo', 'Thames', 'Whangarei', 'Cambridge'] },
      { code: 'BOP', name: 'Bay of Plenty', cities: ['Tauranga', 'Rotorua', 'Whakatane', 'Taupo'] },
      { code: 'HAW', name: 'Hawke\'s Bay', cities: ['Napier', 'Hastings', 'Gisborne', 'Wairoa'] },
      { code: 'MAR', name: 'Marlborough', cities: ['Blenheim', 'Picton', 'Reefton', 'Spotswood'] },
      { code: 'NEL', name: 'Nelson', cities: ['Nelson', 'Richmond', 'Marlborough', 'Motueka'] },
    ],
  },

  // ============ AFRICA (Major Economies Only) ============
  {
    code: 'ZA',
    name: 'South Africa',
    states: [
      { code: 'GP', name: 'Gauteng', cities: ['Johannesburg', 'Pretoria', 'Soweto', 'Randburg', 'Midrand'] },
      { code: 'WC', name: 'Western Cape', cities: ['Cape Town', 'Stellenbosch', 'Paarl', 'George', 'Worcester'] },
      { code: 'KZN', name: 'KwaZulu-Natal', cities: ['Durban', 'Pietermaritzburg', 'Richards Bay', ' Newcastle'] },
      { code: 'EC', name: 'Eastern Cape', cities: ['Port Elizabeth', 'East London', 'Mthatha', 'Grahamstown'] },
      { code: 'FS', name: 'Free State', cities: ['Bloemfontein', 'Bethlehem', 'Welkom', 'Kroonstad'] },
      { code: 'NW', name: 'North West', cities: ['Mahikeng', 'Rustenburg', 'Klerksdorp', 'Potchefstroom'] },
      { code: 'NP', name: 'Limpopo', cities: ['Polokwane', 'Mokopane', 'Thabazimbi', 'Musina'] },
      { code: 'MP', name: 'Mpumalanga', cities: ['Nelspruit', 'Witbank', 'Secunda', 'Middleburg'] },
    ],
  },
]

export function getStatesByCountry(countryCode: string): State[] {
  const country = getCountryByCode(countryCode)
  return country?.states || []
}

export function getCitiesByState(countryCode: string, stateCode: string): string[] {
  const country = getCountryByCode(countryCode)
  const state = country?.states.find(s => s.code === stateCode)
  return state?.cities || []
}
